### ISSUE TITLE
Can not open pretrained model url.

### ISSUE THREAD

**Issue by Huawei-xiaoyi** [simochen/flowtrack.pytorch#1]
hi, I got 404 when opening the pretrained model url(https://github.com/simochen/flowtrack.pytorch/blob/master). Can you provide another model so that I can run your demo. thx...

**Comment by simochen** [comment]
hi, @zhengpengpeng . I fixed the pretrained model url.

**Comment by Huawei-xiaoyi** [comment]
This model works. thx..

**Comment by Huawei-xiaoyi** [comment]
The FlowNet model still has some problems...
FlowNet2-S_checkpoint.pth.tar: The archive is either in unknown format or damaged
Could you fix this?

**Comment by simochen** [comment]
Did you try to untar the model file? The model is used directly.
