### ISSUE TITLE
Can it be used to track multi-person pose?

### ISSUE THREAD

**Issue by lc4321** [simochen/flowtrack.pytorch#4]

**Comment by simochen** [comment]
@Innerpeace90 Yes, the method can be used to tracking multi-person pose. You can refer to [the paper](https://arxiv.org/pdf/1804.06208.pdf) for details.

**Comment by lc4321** [comment]
I’m studying your paper now, there are some questions confused me about the tracking, such as how to  reference optical flow method and the parameters you used in this paper. 3Q very much!

**Comment by lc4321** [comment]
Sorry to disturb you again, do you have the plan to open the codes about tracking?

**Comment by simochen** [comment]
@Innerpeace90 This is not my paper. The official code has not been released yet. I am making efforts to re-implement the method.
