### ISSUE TITLE
Dear author, can you give the examples of "mpii_.json" and "coco_train/val.json" for pose training? 

### ISSUE THREAD

**Issue by Allenwutao** [simochen/flowtrack.pytorch#5]
Dear author, I want to training the pose model. However there are always some errors to use "mpii_.json" and "coco_train/val.json" produced by myself. Can you give some examples of "mpii_.json" and "coco_train/val.json" ?

**Comment by simochen** [comment]
Hi, @Allenwutao. Please see [here](https://drive.google.com/drive/folders/1RqsY3ONtYlxQfLg2acJm36qTtqvHDCik) for the files.
